project:
  type: website
  output-dir: docs
website:
  title: "Material Docente"
  navbar:
    left:
      - href: index.qmd
        text: Inicio
      - href: cursos.qmd
        text: Cursos
      - href: about.qmd
        text: Sobre mí
    right:
      - icon: github
        href: https://github.com/
      - icon: linkedin
        href: https://linkedin.com/

format:
  html:
    theme:
      light: flatly
    toc: true
    smooth-scroll: true
    css: styles.scss
    include-after-body: card-links.js

lang: es
