---
title: "APRENDIZAJE AUTOMATICO"
---

[← Volver a cursos](cursos.qmd)

## Clases y material (PDF)

1. [S1 - Introducción a Machine Learning](material/APRENDIZAJE%20AUTOMATICO/S1_Introducci%C3%B3n%20a%20Machine%20Learning.pdf)
2. [S2 - Regularización en Regresión Lineal, Regresión Logística, y Perceptrón](material/APRENDIZAJE%20AUTOMATICO/S2_Regularizaci%C3%B3n%20en%20Regresi%C3%B3n%20Lineal%2C%20Regresi%C3%B3n%20Log%C3%ADstica%2C%20y%20Perceptr%C3%B3n..pdf)
3. [S3 - Dimensionality Reduction (PCA and LDA)](material/APRENDIZAJE%20AUTOMATICO/S3_Dimensionality%20Reduction(PCA%20and%20LDA).pdf)
4. [S4 - Feature Selection, K-nearest Neighbors & K-means](material/APRENDIZAJE%20AUTOMATICO/S4_Feature%20Selection%20%26%20K-nearest%20Neighbors%20%26%20K-means%20Algorithms.pdf)
5. [S5 - Support Vector Machine](material/APRENDIZAJE%20AUTOMATICO/S5_Support%20Vector%20Machine.pdf)
6. [S5.2 - Support Vector Regression](material/APRENDIZAJE%20AUTOMATICO/S5.2_Support%20Vector%20Regression.pdf)
7. [S6 - Bagging and Boosting](material/APRENDIZAJE%20AUTOMATICO/S6_Bagging%20and%20Boosting.pdf)
8. [S7.1 - Introduction to ML implementation in Hardware](material/APRENDIZAJE%20AUTOMATICO/S7.1_Introduction%20to%20ML%20implementation%20in%20Hardware.pdf)
9. [S7.2 - Hyperparameter tuning with RayTune](material/APRENDIZAJE%20AUTOMATICO/S7_2_Hyperparameter%20tuning%20with%20RayTune.pdf)
