---
title: "DEIA514 VISIÓN COMPUTACIONAL"
---

[← Volver a cursos](cursos.qmd)

## Clases y material (PDF)

1. [W1 - CV Introduction](material/DEIA514%20VISI%C3%93N%20COMPUTACIONAL/W1_CV_Introduction.pdf)
2. [W2 - CV Segmentation](material/DEIA514%20VISI%C3%93N%20COMPUTACIONAL/W2_CV_Segmentation.pdf)
3. [W3 - Object Representation, Local Descriptors, Tracking](material/DEIA514%20VISI%C3%93N%20COMPUTACIONAL/W3_CV_Object_Representation___Local_descriptors___Tracking.pdf)
4. [W4 - Calibration & Geometric Vision](material/DEIA514%20VISI%C3%93N%20COMPUTACIONAL/W4_CV_Calibration___Geometric_Vision.pdf)
5. [W5 - Geometric Vision](material/DEIA514%20VISI%C3%93N%20COMPUTACIONAL/W5_CV_Geometric_Vision.pdf)
6. [Introducción VCA](material/DEIA514%20VISI%C3%93N%20COMPUTACIONAL/Introduccio%CC%81n_VCA.pdf)
7. [Inference Optimizer for Embedded Systems](material/DEIA514%20VISI%C3%93N%20COMPUTACIONAL/Inference_Optimizer_for_Embedded_Systems.pdf)
8. [Optimized CV Algorithms for Embedded Systems](material/DEIA514%20VISI%C3%93N%20COMPUTACIONAL/Optimized_CV_algorithms_for_Efficient_Inference_on_Embedded_Systems.pdf)
