---
title: "EIN087B-Ciencia de Datos"
---

[← Volver a cursos](cursos.qmd)

## Clases y material (PDF)

1. [W1.1 - Introducción](material/EIN087B-Ciencia%20de%20Datos/W1_1___Introducciy%CC%81n.pdf)
2. [W1.2 - Procesamiento y visualización de datos](material/EIN087B-Ciencia%20de%20Datos/W1_2___Procesamiento_y_visualizaciy%CC%81n_de_datos.pdf)
3. [W1.3 - Ciencia de Datos](material/EIN087B-Ciencia%20de%20Datos/W1_3___Ciencia_de_Datos.pdf)
4. [W1.4 - Regresión Lineal](material/EIN087B-Ciencia%20de%20Datos/W1_4__Regresiy%CC%81n_Lineal.pdf)
5. [W1.5 - Evaluación de algoritmos](material/EIN087B-Ciencia%20de%20Datos/W1_5__Evaluacio%CC%81n_de_algoritmos.pdf)
6. [W1.6 - Evaluación de algoritmos en Python](material/EIN087B-Ciencia%20de%20Datos/W1_6__Evaluacio%CC%81n_de_algoritmos_en_Python.pdf)
7. [W1.8 - KMeans y KNN](material/EIN087B-Ciencia%20de%20Datos/W1_8__KMeans_KNN.pdf)
8. [W1.9 - Bagging and Boosting](material/EIN087B-Ciencia%20de%20Datos/W1_9__Bagging_and_Boosting-2.pdf)
9. [W1.10 - Support Vector Machine](material/EIN087B-Ciencia%20de%20Datos/W1_10__Support_Vector_Machine-2.pdf)
10. [W1.11 - Basic Image Processing and Time Series Analysis](material/EIN087B-Ciencia%20de%20Datos/W1_11__Basic_Image_Processing_and_Time_Series_Analysis.pdf)
11. [W1.12 - Deployment](material/EIN087B-Ciencia%20de%20Datos/W1_12__Deployment.pdf)
